## Exercício 1: Vestibular

Considere que a os dados gerados na célula abaixo contêm o número de acertos de 100 alunos em um vestibular para um curso de exatas, divididas pelos respectivos assuntos. Considere que cada assunto possui um número de questões conforme a tabela abaixo:

| assunto | número de questões |
|:---:|:---:|
| Matemática | 24 |
| Português | 18 |
| Geografia | 8 |
| Inglês | 8 |
| História | 8 |
| Física | 12 |
| Química | 12 |

Usando os comandos de operações com DataFrames que você aprendeu na Aula 03, calcule:

1. (operações com escalar) Calcule o percentual de acerto dos alunos por assunto.  
2. (operações entre *DataFrames) Calcule o total de acertos de cada aluno.  
3. Calcule o porcentual geral de cada aluno.  
4. Suponha que a nota de corte para a segunda fase seja 45. Quantos alunos tiveram nota maior que 45?

In [163]:
import pandas as pd
import numpy as np

np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

In [164]:
# 1) Código:

#Cáculo dos percentuais de acerto dos alunos por assunto 
pc_mat = (df_mat / 24)*100
pc_por = (df_por / 18)*100
pc_geo = (df_geo /  8)*100
pc_ing = (df_ing /  8)*100
pc_his = (df_his /  8)*100
pc_fis = (df_fis /  8)*100 
pc_qui = (df_qui /  8)*100

#criando um DataFrame com cada acerto dos alunos por assunto:

pc_mat.columns=['Matemática(%)']
pc_por.columns=['Português(%)']
pc_geo.columns=['Geografia(%)']
pc_ing.columns=['Inglês(%)']
pc_his.columns=['História(%)']
pc_fis.columns=['Física(%)']
pc_qui.columns=['Química(%)']

#Concatenando as colunas para um único DataFrame: método concat():

pc_alunos = pd.concat([pc_mat, pc_por, pc_geo, pc_ing, pc_his, pc_fis, pc_qui], axis=1) # o parâmetro axis concatena colunas, mostrando de forma horizontal, um ao lado do outro.
pd.DataFrame(pc_alunos)

,Matemática(%),Português(%),Geografia(%),Inglês(%),História(%),Física(%),Química(%)
0,25.000000,38.888889,87.5,37.5,12.5,100.0,37.5
1,79.166667,55.555556,0.0,0.0,0.0,137.5,100.0
2,58.333333,88.888889,0.0,62.5,87.5,50.0,50.0
3,41.666667,38.888889,37.5,50.0,0.0,0.0,100.0
4,29.166667,11.111111,25.0,87.5,0.0,112.5,37.5
...,...,...,...,...,...,...,...
95,25.000000,22.222222,87.5,12.5,50.0,112.5,37.5
96,33.333333,5.555556,50.0,75.0,12.5,50.0,37.5
97,95.833333,27.777778,0.0,25.0,50.0,12.5,62.5
98,0.000000,55.555556,37.5,12.5,62.5,125.0,137.5
99,45.833333,83.333333,0.0,12.5,75.0,87.5,25.0

In [165]:
# 2) Código:

total = df_mat + df_por + df_geo + df_ing + df_his + df_fis + df_qui
total

    Qt_acertos
0           35
1           48
2           50
3           32
4           30
..         ...
95          34
96          27
97          40
98          40
99          42

[100 rows x 1 columns]

In [166]:
#Concatenando os DataFrames para a visualização de Dados:

pc_alunos = pd.concat([pc_mat, pc_por, pc_geo, pc_ing, pc_his, pc_fis, pc_qui, total], axis=1) # o parâmetro axis concatena colunas, mostrando de forma horizontal, um ao lado do outro.
pd.DataFrame(pc_alunos)

,Matemática(%),Português(%),Geografia(%),Inglês(%),História(%),Física(%),Química(%),Qt_acertos
0,25.000000,38.888889,87.5,37.5,12.5,100.0,37.5,35
1,79.166667,55.555556,0.0,0.0,0.0,137.5,100.0,48
2,58.333333,88.888889,0.0,62.5,87.5,50.0,50.0,50
3,41.666667,38.888889,37.5,50.0,0.0,0.0,100.0,32
4,29.166667,11.111111,25.0,87.5,0.0,112.5,37.5,30
...,...,...,...,...,...,...,...,...
95,25.000000,22.222222,87.5,12.5,50.0,112.5,37.5,34
96,33.333333,5.555556,50.0,75.0,12.5,50.0,37.5,27
97,95.833333,27.777778,0.0,25.0,50.0,12.5,62.5,40
98,0.000000,55.555556,37.5,12.5,62.5,125.0,137.5,40
99,45.833333,83.333333,0.0,12.5,75.0,87.5,25.0,42

In [167]:
# 3) Código:

perc_geral = total/100 #calculando
perc_geral.columns=['Perc_acertos'] #criando uma nova coluna para os dados
perc_geral

    Perc_acertos
0           0.35
1           0.48
2           0.50
3           0.32
4           0.30
..           ...
95          0.34
96          0.27
97          0.40
98          0.40
99          0.42

[100 rows x 1 columns]

In [168]:
#Concatenando os DataFrames para a visualização de Dados:

pc_alunos = pd.concat([pc_mat, pc_por, pc_geo, pc_ing, pc_his, pc_fis, pc_qui, total, perc_geral], axis=1) # o parâmetro axis concatena colunas, mostrando de forma horizontal, um ao lado do outro.
pd.DataFrame(pc_alunos)

,Matemática(%),Português(%),Geografia(%),Inglês(%),História(%),Física(%),Química(%),Qt_acertos,Perc_acertos
0,25.000000,38.888889,87.5,37.5,12.5,100.0,37.5,35,0.35
1,79.166667,55.555556,0.0,0.0,0.0,137.5,100.0,48,0.48
2,58.333333,88.888889,0.0,62.5,87.5,50.0,50.0,50,0.50
3,41.666667,38.888889,37.5,50.0,0.0,0.0,100.0,32,0.32
4,29.166667,11.111111,25.0,87.5,0.0,112.5,37.5,30,0.30
...,...,...,...,...,...,...,...,...,...
95,25.000000,22.222222,87.5,12.5,50.0,112.5,37.5,34,0.34
96,33.333333,5.555556,50.0,75.0,12.5,50.0,37.5,27,0.27
97,95.833333,27.777778,0.0,25.0,50.0,12.5,62.5,40,0.40
98,0.000000,55.555556,37.5,12.5,62.5,125.0,137.5,40,0.40
99,45.833333,83.333333,0.0,12.5,75.0,87.5,25.0,42,0.42

In [169]:
# 4) Código:

total_gt_45 = total[total['Qt_acertos'] > 45]
total_gt_45.count()

Qt_acertos    31
dtype: int64

## 2) Vestibular II

Ainda sobre o mesmo banco de dados:

1. Neste vestibular, quem 'zera' em matemática, física ou química está desqualificado. Monte um novo *DataFrame* com os alunos desqualificados por este critério.
2. Quantos são esses alunos?
3. Qual a média desses alunos em história e geografia?
4. Monte um *DataFrame* com os alunos que passaram para a segunda fase. Repare que estes alunos não podem ter sido desqualificados.

In [170]:
# Código:

#1. Alunos desqualificados:

eliminados = total[(df_mat['Qt_acertos'] == 0) | 
                      (df_fis['Qt_acertos'] == 0) | 
                      (df_qui['Qt_acertos'] == 0)]

eliminados

    Qt_acertos
3           32
6           29
10          31
12          42
14          31
20          53
25          27
26          40
27          50
33          39
35          48
49          19
56          39
65          24
66          31
72          50
73          37
74          39
84          26
89          63
92          40
94          25
98          40

In [171]:
#2. Quantidade dos alunos eliminados:

eliminados.count()

Qt_acertos    23
dtype: int64

In [172]:
#3. Média dos alunos eliminados, em História e Geografia:

media_hist_geo = (df_his + df_geo) / 2

print("Média das notas de História e de Geografia dos alunos desqualificados:")
media_hist_geo

Média das notas de História e de Geografia dos alunos desqualificados:

    Qt_acertos
0          4.0
1          0.0
2          3.5
3          1.5
4          1.0
..         ...
95         5.5
96         2.5
97         2.0
98         4.0
99         3.0

[100 rows x 1 columns]

In [173]:
#4.  DataFrame com os alunos que passaram para a segunda fase:

alunos_segunda_fase = total[(df_mat['Qt_acertos'] != 0) & 
                              (df_fis['Qt_acertos'] != 0) & 
                              (df_qui['Qt_acertos'] != 0)]

alunos_segunda_fase

    Qt_acertos
0           35
1           48
2           50
4           30
5           50
..         ...
93          56
95          34
96          27
97          40
99          42

[77 rows x 1 columns]

## 3) Vacinações no Acre
Vamos trabalhar agora com a base de vacinações no Acre. Para facilitar a sua vida, copiamos o link do arquivo na célula abaixo.

1. Quantas vacinas estão registradas nessa base?  
2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método ```.unique()```.   
4. Quantos pacientes com menos de 18 anos foram vacinados?  
5. Quantos estabelecimentos aplicaram vacina no Acre?


**OBS:** O portal do DATASUS pode apresentar instabilidades, retornando um erro na segunda célula abaixo. Por este motivo está disponível uma base estática, que se for baixada para o seu *working directory* pode ser lida com este comando: ```df = pd.read_csv('registros de vacinacao covid ACRE.csv', sep=';')```.

**OBS2:** Para saber qual é o seu working directory, rode no jupyter: ```!pwd```.

In [174]:
# Instabilidade do DATASUS:
#arquivo = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SIPNI/COVID/uf/uf%3DAC/part-00000-5ed92752-6121-474f-ab37-816918134afc.c000.csv'

#Base para consulta: 'registro_vacinacao_acre.csv'

In [175]:
# 1) Código: quantas vacinas registradas na base

arquivo = 'registro_vacinacao_acre.csv'
vac_Acre = pd.read_csv(arquivo, sep=';')
vac_Acre.head(5)

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
0,1ac9b249-4025-4415-9fbf-53972798cadb-i0b0,9ad5566f12c112195cb569c0daea23da2848f999989e17...,22,2000-01-29,F,1,BRANCA,120060.0,10.0,TARAUACA,...,2.0,Faixa Etária,FM3355,PFIZER,Organization/28290,2022-02-16,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
1,83264997-78b3-4f35-8b12-67b20c3004c3-i0b0,bd94d3623c928c847877e3757a1a6e9500e16e27cb4325...,45,1976-11-10,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,21PVCD368Z,ASTRAZENECA/FIOCRUZ,149,2022-07-11,2º Reforço,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
2,b7f3b0ad-1d61-44ea-a37e-b9ee50a10365-i0b0,43701bf77265be8940c465b216142854b80baa58fb9ac6...,67,1954-10-08,F,4,AMARELA,120050.0,10.0,SENA MADUREIRA,...,2.0,Faixa Etária,212J21A,JANSSEN,30587,2022-06-21,2º Reforço,88,COVID-19 JANSSEN - Ad26.COV2.S,Novo PNI
3,8343f768-bcb4-4e9a-ae67-85c5764c37eb-i0b0,640ca7d42c2f2123290ea93fc6d9d8a29c6e845395496f...,40,1980-10-01,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,1.0,Comorbidades,213VCD042Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-05-17,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
4,c3af974c-63ae-4948-92c5-a2c5621c1542-i0b0,db0a4cd2d7853d83251885f6de2131869685bc8783d114...,43,1977-12-13,F,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,216VCD213W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-08-09,2ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI

In [176]:
#Verificando os tipos de informação:

vac_Acre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387105 entries, 0 to 387104
Data columns (total 32 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               387105 non-null  object
 1   paciente_id                               387105 non-null  object
 2   paciente_idade                            387105 non-null  int64
 3   paciente_dataNascimento                   387105 non-null  object
 4   paciente_enumSexoBiologico                387105 non-null  object
 5   paciente_racaCor_codigo                   387105 non-null  int64
 6   paciente_racaCor_valor                    387105 non-null  object
 7   paciente_endereco_coIbgeMunicipio         384683 non-null  float64
 8   paciente_endereco_coPais                  384689 non-null  float64
 9   paciente_endereco_nmMunicipio             384688 non-null  object
 10  paciente_endereco_nmPais                  384689 non-null  object
 11  paciente_endereco_uf                      384683 non-null  object
 12  paciente_endereco_cep                     330446 non-null  float64
 13  paciente_nacionalidade_enumNacionalidade  386927 non-null  object
 14  estabelecimento_valor                     387105 non-null  int64
 15  estabelecimento_razaoSocial               387105 non-null  object
 16  estalecimento_noFantasia                  387105 non-null  object
 17  estabelecimento_municipio_codigo          387105 non-null  int64
 18  estabelecimento_municipio_nome            387105 non-null  object
 19  estabelecimento_uf                        387105 non-null  object
 20  vacina_grupoAtendimento_codigo            387105 non-null  int64
 21  vacina_grupoAtendimento_nome              385864 non-null  object
 22  vacina_categoria_codigo                   366475 non-null  float64
 23  vacina_categoria_nome                     366475 non-null  object
 24  vacina_lote                               387105 non-null  object
 25  vacina_fabricante_nome                    387105 non-null  object
 26  vacina_fabricante_referencia              382725 non-null  object
 27  vacina_dataAplicacao                      387105 non-null  object
 28  vacina_descricao_dose                     387105 non-null  object
 29  vacina_codigo                             387105 non-null  int64
 30  vacina_nome                               387096 non-null  object
 31  sistema_origem                            386706 non-null  object
dtypes: float64(4), int64(6), object(22)
memory usage: 94.5+ MB

In [177]:
#Contado o número de vacinas registradas:

num_vacinas = vac_Acre.shape[0] #método shape[0] retorna o número de linhas do DataFrame.
print(f"Quantidade de vacinas registradas: {num_vacinas}")

Quantidade de vacinas registradas: 387105

In [178]:
# 2) Quantos pacientes foram vacinados? (considere um paciente para cada valor único de paciente_id):

vac_Acre.nunique()

document_id                                 387105
paciente_id                                 316469
paciente_idade                                 112
paciente_dataNascimento                      32802
paciente_enumSexoBiologico                       2
paciente_racaCor_codigo                          6
paciente_racaCor_valor                           6
paciente_endereco_coIbgeMunicipio             1547
paciente_endereco_coPais                         6
paciente_endereco_nmMunicipio                 1529
paciente_endereco_nmPais                         6
paciente_endereco_uf                            28
paciente_endereco_cep                         3644
paciente_nacionalidade_enumNacionalidade         3
estabelecimento_valor                          223
estabelecimento_razaoSocial                     62
estalecimento_noFantasia                       232
estabelecimento_municipio_codigo                22
estabelecimento_municipio_nome                  22
estabelecimento_uf                               1
vacina_grupoAtendimento_codigo                  96
vacina_grupoAtendimento_nome                    97
vacina_categoria_codigo                         21
vacina_categoria_nome                           21
vacina_lote                                    361
vacina_fabricante_nome                          13
vacina_fabricante_referencia                    16
vacina_dataAplicacao                          1222
vacina_descricao_dose                           16
vacina_codigo                                   11
vacina_nome                                     12
sistema_origem                                   3
dtype: int64

In [179]:
pacientes_vacinados = vac_Acre['paciente_id'].nunique()
print(f"Quantidade de pacientes vacinados: {pacientes_vacinados}")

Quantidade de pacientes vacinados: 316469

In [180]:
# 3) Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. Receba os valores do campo com o método .unique().

#Campo: vacina_descricao_dose

#Retornando os campos únicos:

doses = vac_Acre['vacina_descricao_dose'].unique()
print("Valores únicos no campo de dose:", doses)

Valores únicos no campo de dose: ['2ª Dose' '2º Reforço' '1ª Dose' 'Reforço' 'Única' '2ª Dose Revacinação'
 'Dose Adicional' 'Dose' '3ª Dose' '1º Reforço' '1ª Dose Revacinação'
 'Revacinação' '3ª Dose Revacinação' '3º Reforço' '4ª Dose Revacinação'
 '5ª Dose Revacinação']

In [181]:
# Filtrando os registros onde a dose é a primeira dose:

primeira_dose = vac_Acre[vac_Acre['vacina_descricao_dose'] == '1ª Dose']

# Contando o número de pacientes únicos que tomaram a primeira dose
numero_de_pacientes_primeira_dose = primeira_dose['paciente_id'].nunique()
print(f"Quantidade de pacientes que tomaram a primeira dose: {numero_de_pacientes_primeira_dose}")

Quantidade de pacientes que tomaram a primeira dose: 143199

In [182]:
# 3) solução alternativa:
numero_de_pacientes_primeira_dose = vac_Acre['vacina_descricao_dose'] == '1ª Dose'
numero_de_pacientes_primeira_dose

0         False
1         False
2         False
3          True
4         False
          ...
387100    False
387101    False
387102     True
387103    False
387104     True
Name: vacina_descricao_dose, Length: 387105, dtype: bool

In [183]:
vac_Acre[numero_de_pacientes_primeira_dose]

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
3,8343f768-bcb4-4e9a-ae67-85c5764c37eb-i0b0,640ca7d42c2f2123290ea93fc6d9d8a29c6e845395496f...,40,1980-10-01,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,1.0,Comorbidades,213VCD042Z,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-05-17,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
8,6ddf68cd-818c-456e-9477-44f916d0c56b-i0b0,fadf14a25a8f6b0bcb3a67646e9c27fe68252e2133e8ba...,20,2000-05-15,M,99,SEM INFORMACAO,120030.0,10.0,FEIJO,...,7.0,Povos Indígenas,202010040,SINOVAC/BUTANTAN,Organization/61189445000156,2021-01-31,1ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
10,7a71fdcb-e9d2-4c9f-9dda-145c9d1bd0d2-i0b0,f9255083444de99d5148d989829b214631a9dcbbbbccd0...,38,1983-02-26,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,1.0,Comorbidades,EW0199,PFIZER,Organization/00394544000851,2021-05-24,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
11,8434f92e-26ae-4869-8772-9dbd6173a51e-i0b0,b4a262ba35863acae08a1df5bd3d6f932b77bdbbd239bd...,37,1986-03-12,F,3,PARDA,120060.0,10.0,TARAUACA,...,6.0,Povos e Comunidades Tradicionais,227VCD154X,ASTRAZENECA/FIOCRUZ,149,2023-03-26,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
15,84a1125a-ada7-4a88-9026-36d905e03e83-i0b0,aa3ba80660a329c9058cf208203f364813fea1cf8ab4b9...,37,1983-12-02,M,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,210320A,SINOVAC/BUTANTAN,Organization/61189445000156,2021-09-24,1ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387094,40db3949-f0d2-4e62-993f-f7f80b573fb0-i0b0,3a77da875130a773fcbbb8f2ea16362a22fd3ea024d1a7...,40,1980-07-11,M,99,SEM INFORMACAO,120060.0,10.0,TARAUACA,...,2.0,Faixa Etária,215VCD120W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-06-16,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI
387096,410b8e5a-93b4-4516-b3aa-f1d22dea049a-i0b0,c1c1c41194be2cf984745fe1296ca44202f523a0bf0942...,23,1997-09-26,F,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,210277,SINOVAC/BUTANTAN,Organization/61189445000156,2021-07-07,1ª Dose,86,COVID-19 SINOVAC/BUTANTAN - CORONAVAC,Novo PNI
387099,413f82e1-3a2c-4c4f-8571-acd87f553cd1-i0b0,660e08b3c9fb865e4923d6d73d5433068e87a7571d4054...,16,2005-04-05,M,1,BRANCA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-09,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
387102,41c24de3-6643-4fc1-a586-ed94e1b56ba8-i0b0,55dc30eaa2f452cd9709c16b196b5171c5e740c77d49c5...,1,2021-11-06,M,3,PARDA,120070.0,10.0,XAPURI,...,2.0,Faixa Etária,GX6964,PFIZER - PEDIÁTRICA MENOR DE 5 ANOS,28290,2023-07-12,1ª Dose,102,COVID-19 PFIZER - COMIRNATY PEDIÁTRICA MENOR D...,Novo PNI
387104,41dc78ee-4619-4cd0-8f71-c6d34d20b9d7-i0b0,87dcad569c93f593267ee2dd9ff40385450f8b72b72720...,43,1977-09-10,M,3,PARDA,120005.0,10.0,ASSIS BRASIL,...,2.0,Faixa Etária,215VCD116W,ASTRAZENECA/FIOCRUZ,Organization/33781055000135,2021-06-26,1ª Dose,85,COVID-19 ASTRAZENECA/FIOCRUZ - COVISHIELD,Novo PNI

In [184]:
# Contando o número de pacientes únicos que tomaram a primeira dose
numero_de_pacientes_primeira_dose = primeira_dose['paciente_id'].nunique()
print(f"Quantidade de pacientes que tomaram a primeira dose: {numero_de_pacientes_primeira_dose}")

Quantidade de pacientes que tomaram a primeira dose: 143199

In [185]:
# 4) Quantos pacientes com menos de 18 anos foram vacinados?

# Filtrar os registros onde a idade é menor que 18
menores_de_18 = vac_Acre[vac_Acre['paciente_idade'] < 18]

# Contar o número de pacientes únicos com menos de 18 anos
numero_de_pacientes_menores_de_18 = menores_de_18['paciente_id'].nunique()
print(f"Quantidade de pacientes com menos de 18 anos vacinados: {numero_de_pacientes_menores_de_18}")

Quantidade de pacientes com menos de 18 anos vacinados: 68216

In [186]:
# 5) Quantos estabelecimentos aplicaram vacina no Acre?

# Contar o número de estabelecimentos distintos
numero_de_estabelecimentos = vac_Acre['estabelecimento_municipio_nome'].nunique()
print(f"Quantidade de estabelecimentos que aplicaram vacinas: {numero_de_estabelecimentos}")

Quantidade de estabelecimentos que aplicaram vacinas: 22

## 4) Vacinação II
Gere um *DataFrame* que contenha somente os estabelecimentos que aplicaram vacinas a menores de 18 anos. Nesse *DataFrame* devem conter somente os dados dos estabelecimentos, mais uma coluna sendo a quantidade de vacinas que o estabelecimento aplicou a menores de 18 anos.  
  
1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
3. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.  
4. usando o método *.loc*, selecione somente essas variáveis  
5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento

In [187]:
vac_Acre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387105 entries, 0 to 387104
Data columns (total 32 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   document_id                               387105 non-null  object
 1   paciente_id                               387105 non-null  object
 2   paciente_idade                            387105 non-null  int64
 3   paciente_dataNascimento                   387105 non-null  object
 4   paciente_enumSexoBiologico                387105 non-null  object
 5   paciente_racaCor_codigo                   387105 non-null  int64
 6   paciente_racaCor_valor                    387105 non-null  object
 7   paciente_endereco_coIbgeMunicipio         384683 non-null  float64
 8   paciente_endereco_coPais                  384689 non-null  float64
 9   paciente_endereco_nmMunicipio             384688 non-null  object
 10  paciente_endereco_nmPais                  384689 non-null  object
 11  paciente_endereco_uf                      384683 non-null  object
 12  paciente_endereco_cep                     330446 non-null  float64
 13  paciente_nacionalidade_enumNacionalidade  386927 non-null  object
 14  estabelecimento_valor                     387105 non-null  int64
 15  estabelecimento_razaoSocial               387105 non-null  object
 16  estalecimento_noFantasia                  387105 non-null  object
 17  estabelecimento_municipio_codigo          387105 non-null  int64
 18  estabelecimento_municipio_nome            387105 non-null  object
 19  estabelecimento_uf                        387105 non-null  object
 20  vacina_grupoAtendimento_codigo            387105 non-null  int64
 21  vacina_grupoAtendimento_nome              385864 non-null  object
 22  vacina_categoria_codigo                   366475 non-null  float64
 23  vacina_categoria_nome                     366475 non-null  object
 24  vacina_lote                               387105 non-null  object
 25  vacina_fabricante_nome                    387105 non-null  object
 26  vacina_fabricante_referencia              382725 non-null  object
 27  vacina_dataAplicacao                      387105 non-null  object
 28  vacina_descricao_dose                     387105 non-null  object
 29  vacina_codigo                             387105 non-null  int64
 30  vacina_nome                               387096 non-null  object
 31  sistema_origem                            386706 non-null  object
dtypes: float64(4), int64(6), object(22)
memory usage: 94.5+ MB

In [188]:
vac_Acre.columns.unique()

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_dataNascimento', 'paciente_enumSexoBiologico',
       'paciente_racaCor_codigo', 'paciente_racaCor_valor',
       'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais',
       'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaoSocial', 'estalecimento_noFantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoAtendimento_codigo',
       'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataAplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem'],
      dtype='object')

In [189]:
# 1) Criando uma cópia do DataFrame original, contendo somente os registros de vacinas realizadas a menores de 18 anos.

# Filtrando registros onde a idade do paciente é menor que 18 anos
menores_de_18 = vac_Acre[vac_Acre['paciente_idade'] < 18]

# Agrupando por estabelecimento e contar o número de vacinas aplicadas a menores de 18 anos
estabelecimentos_menores_de_18 = menores_de_18.groupby('estabelecimento_municipio_nome')['vacina_descricao_dose'].count().reset_index()
estabelecimentos_menores_de_18.columns = ['estabelecimento_municipio_nome', 'quantidade_vacinas_menores_de_18']

# Exibindo o DataFrame com os estabelecimentos e a quantidade de vacinas aplicadas a menores de 18 anos
print(estabelecimentos_menores_de_18)

   estabelecimento_municipio_nome  quantidade_vacinas_menores_de_18
0                      ACRELANDIA                               915
1                    ASSIS BRASIL                              1362
2                       BRASILEIA                              1351
3                          BUJARI                              1458
4                        CAPIXABA                               608
5                 CRUZEIRO DO SUL                              8068
6                  EPITACIOLANDIA                               886
7                           FEIJO                              5313
8                          JORDAO                              2709
9                     MANCIO LIMA                              2177
10                  MANOEL URBANO                              1074
11           MARECHAL THAUMATURGO                              2730
12              PLACIDO DE CASTRO                              1376
13                     PORTO ACRE                              1211
14                   PORTO WALTER                              1445
15                     RIO BRANCO                             28842
16                RODRIGUES ALVES                               898
17            SANTA ROSA DO PURUS                              1321
18                 SENA MADUREIRA                              3421
19               SENADOR GUIOMARD                              2344
20                       TARAUACA                              5301
21                         XAPURI                              2447

In [190]:
# Criando cópia do DataFrame original para registros de vacinas a menores de 18 anos
vac_Acre_menores_de_18 = vac_Acre[vac_Acre['paciente_idade'] < 18].copy()

# Exibindo as primeiras linhas do novo DataFrame para verificar
vac_Acre_menores_de_18.head()

,document_id,paciente_id,paciente_idade,paciente_dataNascimento,paciente_enumSexoBiologico,paciente_racaCor_codigo,paciente_racaCor_valor,paciente_endereco_coIbgeMunicipio,paciente_endereco_coPais,paciente_endereco_nmMunicipio,...,vacina_categoria_codigo,vacina_categoria_nome,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataAplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem
14,8f7bce1d-e9ba-4f79-b6b1-58a48f1fc30f-i0b0,39be6074c0def2f70a950d32c04f8e166e08e69fb7c93c...,6,2017-02-08,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,2.0,Faixa Etária,230147,BUTANTAN,152,2023-12-15,Única,33,INF3,Novo PNI
19,84d4971b-909b-4440-a894-87e7d93b4ec5-i0b0,663a41a5d0d44459b590558d9c59429e5197a51d05dace...,6,2015-06-10,F,3,PARDA,120035.0,10.0,MARECHAL THAUMATURGO,...,NaN,NaN,FP8290,Pendente Identificação,Organization/28290,2022-04-27,2ª Dose,99,COVID-19 PEDIÁTRICA - PFIZER COMIRNATY,Novo PNI
24,70378a6a-3ff0-435c-9f51-c61a9df5edab-i0b0,eb2b213d7e48925ec3ceca3c67f98b9704ebf21867ef0b...,17,2004-05-13,F,3,PARDA,120020.0,10.0,CRUZEIRO DO SUL,...,114.0,Outros,FD7207,PFIZER,Organization/00394544000851,2021-08-23,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
43,8665d602-5a61-4e35-9233-155f9affc30c-i0b0,9833139c8aaf3c2d1fbb35d1e38aebbbbcb75b84b510c1...,12,2009-02-08,M,4,AMARELA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FL1939,PFIZER,Organization/28290,2021-12-28,2ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI
57,8711d34c-ba96-4f8b-bc3d-d05a9e0dbdca-i0b0,b94115b6e7bbaefad3857ba5c5a215d05ea3da4b58389d...,14,2007-08-09,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,2.0,Faixa Etária,FA9096,PFIZER,Organization/00394544000851,2021-08-10,1ª Dose,87,COVID-19 PFIZER - COMIRNATY,Novo PNI

In [191]:
# 2) criando uma lista das colunas desse DataFrame com o atributo de DataFrame .columns()

# Obtendo a lista das colunas do DataFrame
colunas = vac_Acre.columns.tolist()

# Exibindo a lista das colunas
print(colunas)

['document_id', 'paciente_id', 'paciente_idade', 'paciente_dataNascimento', 'paciente_enumSexoBiologico', 'paciente_racaCor_codigo', 'paciente_racaCor_valor', 'paciente_endereco_coIbgeMunicipio', 'paciente_endereco_coPais', 'paciente_endereco_nmMunicipio', 'paciente_endereco_nmPais', 'paciente_endereco_uf', 'paciente_endereco_cep', 'paciente_nacionalidade_enumNacionalidade', 'estabelecimento_valor', 'estabelecimento_razaoSocial', 'estalecimento_noFantasia', 'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome', 'estabelecimento_uf', 'vacina_grupoAtendimento_codigo', 'vacina_grupoAtendimento_nome', 'vacina_categoria_codigo', 'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome', 'vacina_fabricante_referencia', 'vacina_dataAplicacao', 'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome', 'sistema_origem']

In [192]:
# 3) Contagem do campo vacina_categoria_nome:

# Contando a quantidade de cada categoria de vacina:

contagem_categorias = vac_Acre['vacina_categoria_nome'].value_counts()

# Exibindo a contagem:

print("Contagem de categorias de vacina:")
print(contagem_categorias)

Contagem de categorias de vacina:
vacina_categoria_nome
Faixa Etária                                       271544
Comorbidades                                        24836
Trabalhadores de Saúde                              15064
Povos Indígenas                                     12643
Povos e Comunidades Tradicionais                    10924
Trabalhadores da Educação                           10045
Outros                                               4456
Trabalhadores Industriais                            3808
População Privada de Liberdade                       2766
Pessoas de 60 anos ou mais institucionalizadas       2653
Pessoas com Deficiência                              2086
Forças de Segurança e Salvamento                     1636
Gestantes                                            1321
Trabalhadores de Transporte                           885
Funcionário do Sistema de Privação de Liberdade       747
Forças Armadas (membros ativos)                       466
Trabalhadores de Limpeza Urbana                       248
Puérperas                                             247
Pessoas em Situação de Rua                             68
Pessoas Institucionalizadas                            22
Trabalhadores Portuários                               10
Name: count, dtype: int64

In [193]:
# 4) a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento, faça uma lista com esses valores.

# Obter lista de todas as colunas do DataFrame
colunas_totais = vac_Acre.columns.tolist()
colunas_totais

['document_id',
 'paciente_id',
 'paciente_idade',
 'paciente_dataNascimento',
 'paciente_enumSexoBiologico',
 'paciente_racaCor_codigo',
 'paciente_racaCor_valor',
 'paciente_endereco_coIbgeMunicipio',
 'paciente_endereco_coPais',
 'paciente_endereco_nmMunicipio',
 'paciente_endereco_nmPais',
 'paciente_endereco_uf',
 'paciente_endereco_cep',
 'paciente_nacionalidade_enumNacionalidade',
 'estabelecimento_valor',
 'estabelecimento_razaoSocial',
 'estalecimento_noFantasia',
 'estabelecimento_municipio_codigo',
 'estabelecimento_municipio_nome',
 'estabelecimento_uf',
 'vacina_grupoAtendimento_codigo',
 'vacina_grupoAtendimento_nome',
 'vacina_categoria_codigo',
 'vacina_categoria_nome',
 'vacina_lote',
 'vacina_fabricante_nome',
 'vacina_fabricante_referencia',
 'vacina_dataAplicacao',
 'vacina_descricao_dose',
 'vacina_codigo',
 'vacina_nome',
 'sistema_origem']

In [194]:
# Filtrando para  as colunas de estabelecimento presentes no DataFrame
colunas_estabelecimento_presentes = [col for col in colunas_estabelecimento if col in colunas_totais]

# Exibindo a lista das colunas relacionadas ao estabelecimento

print("Colunas relacionadas ao estabelecimento:")
print(colunas_estabelecimento_presentes)

Colunas relacionadas ao estabelecimento:
['estabelecimento_valor', 'estabelecimento_razaoSocial', 'estalecimento_noFantasia', 'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome', 'estabelecimento_uf']

In [195]:
# 5) Método loc:

estabelecimento_df = vac_Acre.loc[:, colunas_estabelecimento]
estabelecimento_df

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,3810771,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE DE S DA FAMILIA DR JOSE LEONCIO GOMES ...,120060,TARAUACA,AC
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
2,3007367,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE AGUINALDO NUNES DE OLI...,120050,SENA MADUREIRA,AC
3,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
4,2000598,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE BASICA DE SAUDE GEOVANA MARIA FREITAS ...,120020,CRUZEIRO DO SUL,AC
...,...,...,...,...,...,...
387100,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387101,2002132,PREFEITURA MUN DE MAL THAUMATURGO,ESF RIBEIRINHA DR NALDIR MARIANO,120035,MARECHAL THAUMATURGO,AC
387102,2001934,PREFEITURA MUNICIPAL DE XAPURI,UNIDADE DE SAUDE DA FAMILIA JOSE RAIMUNDO DE MELO,120070,XAPURI,AC
387103,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
387104,2003066,PREFEITURA MUNICIPAL DE ASSIS BRASIL,UNIDADE BASICA DE SAUDE TEREZINHA BATISTA DOS ...,120005,ASSIS BRASIL,AC

In [196]:
#6) Aplique o método .drop_duplicates e crie uma lista com uma linha para cada estabelecimento, com os dados do estabelecimento:

# Selecionando somente as colunas relacionadas ao estabelecimento
estabelecimento_df = vac_Acre.loc[:, colunas_estabelecimento]

# Removendo linhas duplicadas com base nos dados do estabelecimento
estabelecimento_df = estabelecimento_df.drop_duplicates()

# Exibindo o DataFrame resultante
estabelecimento_df

,estabelecimento_valor,estabelecimento_razaoSocial,estalecimento_noFantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
0,3810771,PREFEITURA MUNICIPAL DE TARAUACA,UNIDADE DE S DA FAMILIA DR JOSE LEONCIO GOMES ...,120060,TARAUACA,AC
1,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
2,3007367,PREFEITURA MUNICIPAL DE SENA MADUREIRA,UNIDADE BASICA DE SAUDE AGUINALDO NUNES DE OLI...,120050,SENA MADUREIRA,AC
4,2000598,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE BASICA DE SAUDE GEOVANA MARIA FREITAS ...,120020,CRUZEIRO DO SUL,AC
6,5710111,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,UNIDADE DE SAUDE DA FAMILIA NESTOR SOARES DE V...,120020,CRUZEIRO DO SUL,AC
...,...,...,...,...,...,...
178869,6801099,CENTRO DE DIAGNOSTICOS CITOLAB LTDA,CITOLAB,120020,CRUZEIRO DO SUL,AC
235356,9846433,PREFEITURA MUNICIPAL DE MANOEL URBANO,UNIDADE BASICA DE SAUDE MILTON AUGUSTO DA SILVA,120034,MANOEL URBANO,AC
296181,3393984,PRFEITURA MUNICIPAL DE ACRELANDIA,UNIDADE DE SAUDE DA FAMILIA RICARDO MONTEIRO ROLA,120001,ACRELANDIA,AC
330891,2001322,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOSE FRANCISCO DO NASCIMENTO,120025,EPITACIOLANDIA,AC
381903,7565089,PREFEITURA MUNICIPAL DE RIO BRANCO,USF MARIA DE JESUS III,120040,RIO BRANCO,AC